# Generated by Django 2.0.6 on 2018-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waqt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Dhaka', max_length=127)),
                ('day', models.CharField(help_text='unix format for day (%d)', max_length=2)),
                ('month', models.CharField(help_text='unix format for month (%m)', max_length=2)),
                ('fazr', models.CharField(max_length=15)),
                ('sunrise', models.CharField(max_length=15)),
                ('juhr', models.CharField(max_length=15)),
                ('asr', models.CharField(max_length=15)),
                ('magrib', models.CharField(max_length=15)),
                ('isha', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waqt',
            },
        ),
        migrations.CreateModel(
            name='WaqtStringFromExternalWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waqt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waqt_string',
            },
        ),
    ]
