# Generated by Django 2.0.6 on 2018-06-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthWiseWaqtString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Dhaka', max_length=127)),
                ('month', models.CharField(help_text='unix format for month (%m)', max_length=2)),
                ('waqt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'month_wise_waqt_string',
            },
        ),
        migrations.DeleteModel(
            name='WaqtStringFromExternalWeb',
        ),
    ]
