# Generated by Django 2.0.6 on 2018-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_auto_20180616_0644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthWiseWaqtString',
        ),
        migrations.AlterModelOptions(
            name='waqt',
            options={'ordering': ['month', 'day']},
        ),
        migrations.AlterField(
            model_name='waqt',
            name='day',
            field=models.IntegerField(blank=True, help_text='unix format for day (%d)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='waqt',
            name='month',
            field=models.IntegerField(blank=True, help_text='unix format for month (%m)', max_length=2, null=True),
        ),
    ]
