# Generated by Django 2.0.6 on 2018-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0004_auto_20180616_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waqt',
            name='day',
            field=models.IntegerField(blank=True, help_text='unix format for day (%d)', null=True),
        ),
        migrations.AlterField(
            model_name='waqt',
            name='month',
            field=models.IntegerField(blank=True, help_text='unix format for month (%m)', null=True),
        ),
    ]
