# Generated by Django 2.0.6 on 2018-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0005_auto_20180616_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqt',
            name='year',
            field=models.IntegerField(blank=True, help_text='unix format for month (%Y)', null=True),
        ),
    ]
