# Generated by Django 2.0.6 on 2018-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0007_auto_20180616_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waqt',
            name='year',
            field=models.IntegerField(default=2018, help_text='unix format for month (%Y)'),
        ),
    ]
