# Generated by Django 2.0.6 on 2018-06-16 16:42

import countdown.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0008_auto_20180616_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waqt',
            name='year',
            field=models.IntegerField(default=countdown.models.get_current_year, help_text='unix format for month (%Y)'),
        ),
    ]
